### ISSUE TITLE
Again Syntax Error

### ISSUE THREAD

**Issue by warriorx86** [Sangram2905/NSE_Option_Chain#4]
Again getting syntax error in spyder is well. 
![Spyder Syntax](https://user-images.githubusercontent.com/40427773/115982042-c8b68300-a5b5-11eb-9a99-213c5f2754f1.png)

**Comment by Sangram2905** [comment]
I dont get this error when I run the same file. May be you somehow downloaded the GitHub HTML file for NSE_Option_OI_Analyzer_Bot_Apr2021_Github_R6.py ,  rather than the script itself. 
Delete the NSE_Option_OI_Analyzer_Bot_Apr2021_Github_R6.py file, then re-download it using Spyder on same download folder as working  directory.

try to do Simple google search will resolve the issue, if still have the issue then plz try the original program of https://github.com/VarunS2002/Python-NSE-Option-Chain-Analyzer  and modify the program as per your requirement .

the Varun program is much more functions than my.
